### ISSUE TITLE
Invalid URL on a certain Homepage Subpage

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#556] opened 2021-10-15 15:58 UTC
The page in question: https://demo.tasvideos.org/HomePages/Noxxa/Rankings/Yearly/20042009
Working page on old site: http://tasvideos.org/Noxxa/Rankings/Yearly/20042009.html

An idea why this specific URL fails is because the subpage name is a number.

**Comment by adelikat** [comment] 2021-10-17 17:20
Closing this as "by design".  We can easily fix pages that are numbers only in production now.

**Closed by adelikat** 2021-10-17 17:20 UTC
Labels: Wiki System
