### ISSUE TITLE
Cyrillic comments in page history are broken

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#728] opened 2022-01-02 10:39 UTC
https://tasvideos.org/Wiki/PageHistory?path=RU%2FWelcomeToTASVideos

It's common for translators to write edit notes in their native language, and if we want to support translations better, we want them to be able to do that. And because it has already been done too.

**Comment by msikma** [comment] 2022-01-04 12:13
It seems these values have been interpreted as though they're `cp1252`.

E.g. (in Python):

```python
>>> 'Ð¤Ð¸Ð»ÑŒÐ¼ Ð¾Ñ‚ StopGame.Ru'.encode('cp1252').decode('utf8')
'Фильм от StopGame.Ru'
```

**Comment by vadosnaprimer** [comment] 2022-01-04 12:16
Indeed! The result is proper russian! I couldn't find this out because notepad++ only has cp1251 for cyrillic.

**Comment by msikma** [comment] 2022-01-04 12:35
I had a quick look and couldn't see any other examples of broken Unicode, but here's a quick script that can help figure out the right encoding if it comes up again: https://gist.github.com/msikma/e712ad4c1c27208cae7ad347c934acfe

**Comment by Masterjun3** [comment] 2022-01-05 16:58
There are other places where this happens, and it's the same problem.

Last post:
![image](https://user-images.githubusercontent.com/22375320/148143420-11d5208b-4f6c-4a94-b65a-bc70016f6f37.png)

"last edited by":
![image](https://user-images.githubusercontent.com/22375320/148253493-5afc4280-287c-4e09-b623-c003adcb106a.png)

Revision Author:
![image](https://user-images.githubusercontent.com/22375320/148253552-d9edfab4-5636-4f10-b590-96a4d0153990.png)

**Comment by Masterjun3** [comment] 2022-01-05 17:00
The problem is the database itself. New posts, new revisions, all support proper encoding.

(image from a revision example test):
![image](https://user-images.githubusercontent.com/22375320/148257801-557aa985-151e-4604-91ee-952548b17538.png)

**Comment by adelikat** [comment] 2022-01-05 17:03
Please determine which database tables and columns are effected please

**Comment by adelikat** [comment] 2022-01-07 01:26
Should be fixed now

**Closed by adelikat** 2022-01-07 01:26 UTC
Labels: bug, Priority: Critical
