### ISSUE TITLE
On the Filter Page Retain the Previous Filter.

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/tasvideos#1224] opened 2022-04-09 06:20 UTC
Just to explain it.

Let's say I've selected System, and ObsOnly in this instance, but it turns out that I wanted a different system (or multiple), or select a specific year/timeframe. I rather not want to re-select what I already filtered for.

----

Edit: This also includes from just the Movies page as an example where you select a system, and you want to refine it, and well it loses the system you pre-selected.

**Comment by adelikat** [comment] 2022-09-02 01:41
Closing this a as a duplicate of https://github.com/TASVideos/tasvideos/issues/627
This is an important thing to build, but I think that ticket describes it well enough, and if not, we now have a link to this

**Closed by adelikat** 2022-09-02 01:41 UTC
Labels: Publication System, Priority: Medium
