### ISSUE TITLE
Users/List search + space

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#1150] opened 2022-03-11 21:12 UTC
Adding space before or after username doesn't disable Go button.

1. https://tasvideos.org/Users/List
2. Click on Search and write SSS (capital letters) to find user named SSS
3. Add spaces before and/or after user's name
4. Click on Go or press Enter
5. 404 error https://tasvideos.org/Users/Profile?name=+++SSS+++

Very minimal issue, but it would be nicer if the Go button get disabled if there isn't such user named with what currently the form has.

**Comment by nattthebear** [comment] 2022-03-11 23:14
Hmm, why were we trimming whitespace in this box in the first place?  It makes everything kind of awkward

**Comment by adelikat** [comment] 2022-03-11 23:45
Well, it makes more sense to trim whitespace when it isn't a legal for a user name, which is was never supposed to be

**Comment by nattthebear** [comment] 2022-03-11 23:47
Ahh does that mean there are no users with whitespace in their name?  That would make the fix for this easier -- don't trim, just don't allow whitespace in that box in the first place.

**Comment by vadosnaprimer** [comment] 2022-03-12 06:35
There's a bunch of users with space in the name, a whole bunch of them registered after new site launch.

**Comment by Invariel** [comment] 2022-03-12 06:53
Trimming whitespace is different than removing whitespace.  Trimming is just at the ends, it does not remove internal spaces.

Though, there is a problem if we allow a username like "Dave " or "                 xXx Gamer God 420_69 xXx                 ".

**Comment by meshuggahtas** [comment] 2022-03-12 07:24
> "Dave " or "       xXx Gamer God 420_69 xXx       ".
- I assume that we don't want to allow either of starting/ending space for user names.
- I checked every user name visually (read through them using Users/List) and I don't know of an existing user name which has one of these spaces. Of course it should be checked again straight from the DB

**Comment by nattthebear** [comment] 2022-03-12 10:42
> There's a bunch of users with space in the name, a whole bunch of them registered after new site launch.

So is that a bug or intended behavior?

> Trimming whitespace is different than removing whitespace. Trimming is just at the ends, it does not remove internal spaces.

Yes of course, so that's why I'm trying to understand the expectations here; what is supposed to be allowed in usernames?

**Comment by meshuggahtas** [comment] 2022-03-12 11:19
> what is supposed to be allowed in usernames?

Not decided AFAIK.

Relevant user naming issues:
- https://github.com/TASVideos/tasvideos/issues/119
- My 2nd minimized comment shows known problems, can't link it because it's minimized
- IIRC adelikat said he doesn't likes spaces. I think it's okay to have them. Spaces seems to work very well according to my tests and not allowing spaces might make some users to register with other characters to be used instead of space. Hypothetical example: This_site_is_awesome
- I assume there is a regex pattern in the DB under users_disallow but it's empty for me

**Closed** 2022-10-30 20:59 UTC
Labels: Priority: Bottom
