### ISSUE TITLE
Automatic downscaling of profile pictures

### ISSUE THREAD

**Issue by moozooh** [TASVideos/tasvideos#1711] opened 2023-10-13 21:04 UTC
It's a persistent issue that some users fail to downscale their profile pictures by themselves, and the site itself does nothing to enforce maximum dimensions of profile pictures.

From what I've seen on other sites and social networks, the technology to downscale images automatically indeed exists by this point. Ideally, it should be used. Failing that, the site should simply not accept images bigger than the allowed limits (currently 125×125) at all instead of trusting the user to do their due diligence.

Some message to inform the user should be shown in either case.

**Comment by Masterjun3** [comment] 2023-10-14 00:02
The problem here is that we currently simply allow a string to be the image link. We don't save it ourselves #227 .
The server does not visit this link, or even validate that it's an image at all.
Giving users the ability to make our server visit an arbitrary page is dangerous and probably unwanted. So I think this issue ticket is impossible without hosting images ourselves.

**Comment by YoshiRulz** [comment] 2023-10-14 01:16
I agree, but consider that passing along an arbitrary user-provided URI to other users means any attack would just hit them instead...

**Comment by moozooh** [comment] 2023-10-14 02:13
> The problem here is that we currently simply allow a string to be the image link. We don't save it ourselves #227 . The server does not visit this link, or even validate that it's an image at all. Giving users the ability to make our server visit an arbitrary page is dangerous and probably unwanted. So I think this issue ticket is impossible without hosting images ourselves.

In that case, shouldn't it be possible to limit it in the markup? I.e. giving the space in which the picture would be displayed a fixed maximum width?

**Comment by Spikestuff** [comment] 2023-10-14 02:47
Wouldn't it be easier to just switch it around with?:
![bigavatar](https://tasvideos.org/images/bigavatar.png)

**Comment by CasualPokePlayer** [comment] 2023-10-14 02:55
The fundemental issue is the site does not (and should not) visit the image link, so it cannot do any kind of size detection here. In any case, you have to be uploading the image to the site for any kind of automatic action to be taken.

**Comment by YoshiRulz** [comment] 2023-10-14 04:18
I think @moozooh was suggesting that the user('s browser) includes a fixed size when submitting the URI. That would fix the problem of oversized images, but wouldn't change the situation w.r.t. third-party hosting.

**Comment by Masterjun3** [comment] 2023-10-14 07:59
> In that case, shouldn't it be possible to limit it in the markup? I.e. giving the space in which the picture would be displayed a fixed maximum width?

If you mean just changing our html to have a maximum width, yes that would work and is simple. But we intentionally do not want that.
We *want* to notice if an image is too large. The problem is that the filesize for large images is usually too big as well. If we hide the problem, our pages would load slower as more large images go unnoticed.
The good thing about our ~125 pixel limit is that the filesize automatically goes down to reasonable levels.

**Comment by vadosnaprimer** [comment] 2024-01-04 11:35
So this is all "by design" then?

**Comment by Masterjun3** [comment] 2024-01-04 13:49
Yes. I will close this, since we can't currently implement it.
Instead, I made a new issue with something we can implement here #1732 .

**Closed by Masterjun3** 2024-01-04 13:49 UTC
Labels: enhancement, User/Role Administration System, Forum System

**Comment by YoshiRulz** [comment] 2025-01-27 20:20
Memory-safe alternative to ImageMagick: https://github.com/google/wuffs
