### ISSUE TITLE
Some translated pages disappeared

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#845] opened 2022-01-07 09:37 UTC
https://tasvideos.org/RU _automatically_ lists subpages, and among them you can see

https://tasvideos.org/RU/GameResources
https://tasvideos.org/RU/MovieRules
https://tasvideos.org/RU/TasingGuide

But those pages don't exist anymore somehow. And I don't know how to find them.

**Comment by adelikat** [comment] 2022-01-08 03:40
Are you sure they existed? They are not in the database in any capacity, and best I can tell, all pages were ported over

**Comment by adelikat** [comment] 2022-01-08 03:41
All of those have supages, but they themselves did not exist in the old site either.  Confirmed on legacy site

**Comment by Masterjun3** [comment] 2022-01-08 03:43
RU/MovieRules did exist.
https://web.archive.org/web/20201024142840/http://tasvideos.org/RU/MovieRules.html

**Comment by Masterjun3** [comment] 2022-01-08 03:47
Ah, but that was before the Movie Rules rewrite. Ignore me.

**Comment by vadosnaprimer** [comment] 2022-01-08 08:56
If they don't exist then how do they **automatically** appear as subpages?

**Comment by adelikat** [comment] 2022-01-14 15:51
The listlanguages module assumes parents exist if children do.  I'm happy with this assumption because it makes it faster, and because they SHOULD exist, it is bad design to do otherwise.  Closing this ticket as we have confirmed no pages were lost, and the module is behaving as intended

**Closed by adelikat** 2022-01-14 15:51 UTC
Labels: bug, Priority: Medium
