### ISSUE TITLE
April Fools text not appear on https://tasvideos.org/Profile/UserFiles

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#1212] opened 2022-04-01 10:19 UTC
Literally broken

edit: and sometimes I don't get it on Mobile Firefox. Tested main page and Search. It supposed to be under the menu, but for whatever reason it doesn't appears.

**Comment by SamsaraTAS** [comment] 2022-04-01 10:44
Is there such a thing as negative priority?

**Comment by Masterjun3** [comment] 2022-04-01 10:54
Duplicate of #1212.

**Comment by Masterjun3** [comment] 2022-04-02 13:30
April Fools Day and the joke is over.

**Closed by Masterjun3** 2022-04-02 13:30 UTC
