### ISSUE TITLE
Registration form timezone dropdown loses value on error

### ISSUE THREAD

**Issue by Henny022** [TASVideos/tasvideos#1362] opened 2022-07-06 10:58 UTC
Whenever I hit an error trying to register (see my other two issues) the timezone dropdown would reset its value to the default `Africa/Blantyre`.
The other fields (with the exception of password) all kept my entered values as expected.
I was unable to confirm if this was just a visual bug.
This might very well be a problem with my browser, I'm using `Firefox 102.0 (64bit)` on Windows 10.

**Comment by adelikat** [comment] 2022-07-06 13:28
Closing this as a duplicate of #1159

**Closed by adelikat** 2022-07-06 13:28 UTC
