### ISSUE TITLE
Search box in Navbar

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#1184] opened 2022-03-22 17:25 UTC
Saw this complaint on discord but nobody made at ticket.  Currently  you have a link to a search page.  Instead it could be a box.  The implementation should be easy since the search page links back to itself anyway, using the search in the query string

**Comment by despoa** [comment] 2022-03-23 00:28
I mentioned this in #721

**Comment by TiKevin83** [comment] 2022-03-23 01:05
closing duplicate of #721

**Closed by TiKevin83** 2022-03-23 01:05 UTC
