### ISSUE TITLE
Potential site parser error for .dsm files

### ISSUE THREAD

**Issue by DrD2k9** [TASVideos/tasvideos#2037] opened 2024-11-12 20:07 UTC
The site appears to parse .dsm files that have the line "savestate 0" in the header as starting from a "Savestate" even when they are actually starting from "Power On."

Example: The original file for https://tasvideos.org/9336S has the "savestate 0" line in it and displays as starting from a Savestate.  Removing the "savestate 0" line changes the display to read that the run starts from "Power On."

feos mentioned in Discord that the .dsm file format was changed and that the site parser may not have been updated for proper parsing.

**Comment by adelikat** [comment] 2024-11-12 20:47
is the value 1 when it does start from savestate?

**Comment by vadosnaprimer** [comment] 2024-11-12 20:48
Yes, and a savestate file is then created near the movie.

**Comment by adelikat** [comment] 2024-11-12 20:49
I was under the impression the savestate was in the movie file? was it for old movies? we need to consider every version of .dsm

**Comment by CasualPokePlayer** [comment] 2024-11-12 21:07
This is a duplicate of https://github.com/TASVideos/tasvideos/issues/2006

See https://github.com/TASVideos/tasvideos/issues/2006#issuecomment-2403456350

**Closed by CasualPokePlayer** 2024-11-12 21:07 UTC

**Comment by adelikat** [comment] 2024-11-12 22:43
Seems like the solution here is to add logic that if it the value is 0, then it does not start with savestate?

**Comment by CasualPokePlayer** [comment] 2024-11-12 22:52
Looking back in DeSmuMe's code also seems to indicate the capability to start from the savestate was not exposed in the frontend at all (only present in the core movie recording code, I assume due to it being a copy paste of FCEUX's code). The same time it was exposed in the frontend is the same time it was changed to be a boolean flag with the savestate being separate.
