### ISSUE TITLE
Wiki pre monospace problem

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#1229] opened 2022-04-11 11:06 UTC
I don't know what is the intended feature, but ascii arts seems wrong when using pre to have monospace (equally proportioned distance and size between all characters).

Here's an ascii art with monospace (single space in front of line) which shows that some characters are way too long vertically and makes the lines fall through the next.

https://tasvideos.org/SandBox?revision=16

edit: the original page I copied from to compare with (note, it's not monospace in the original)
https://textart4u.blogspot.com/2012/03/mario-text-art-ascii-art.html 6th Mario on the page

edit2: 
- android firefox and android firefox desktop version: horizontal and vertical space is smaller than other characters
- windows firefox: close to being perfect but still bit smaller than other characters
- windows chrome: some characters fall through next line

**Comment by nattthebear** [comment] 2022-04-12 00:35
Could you post a screenshot from somewhere where it looks bad?

**Comment by MemoryTAS** [comment] 2022-04-12 00:36
is there anywhere where ascii art is prominently used besides the sandbox?

**Comment by meshuggahtas** [comment] 2022-04-12 06:04
[TextFormattingRules says: Please use preformatted text for program source code and such only.](https://tasvideos.org/TextFormattingRules#PreformattedText)

Working ASCII art:
- Safari
![safari_iphone](https://user-images.githubusercontent.com/31288337/162891198-45ea5f53-2572-476f-a2d4-faed014c9f0f.PNG)

Not working ASCII art:
- Windows Chrome
![windows_chrome_monospace](https://user-images.githubusercontent.com/31288337/162891263-0ebed262-9648-4d9e-af8a-fcbd3680417d.PNG)

- Windows Firefox
![windows_firefox_monospace](https://user-images.githubusercontent.com/31288337/162891318-c454cafe-0bee-4d46-b69a-3b056716460c.PNG)

- Android Chrome
![Screenshot_2022-04-12-07-54-16-959_com android chrome](https://user-images.githubusercontent.com/31288337/162891456-7826ef09-dc85-48db-a93f-f49cb7978427.jpg)

- Android Chrome + Desktop version
![Screenshot_2022-04-12-07-54-33-768_com android chrome](https://user-images.githubusercontent.com/31288337/162891478-41707748-bd02-4b65-ba55-af45e9dcad0d.jpg)

- Android Firefox
![Screenshot_2022-04-12-07-53-00-363_org mozilla firefox](https://user-images.githubusercontent.com/31288337/162891499-f51a2dc3-54da-4195-b456-c5ccca601be1.jpg)

- Android Firefox + Desktop version
![Screenshot_2022-04-12-07-53-50-026_org mozilla firefox](https://user-images.githubusercontent.com/31288337/162891519-d34027bd-a161-4559-940f-d9be01299299.jpg)

**Comment by SamsaraTAS** [comment] 2022-04-12 06:51
It's great that you're involved in helping out the site, but my dude, this is literally "ASCII art is slightly misshapen". Issues on this tracker should be things that could conceivably affect the average user using the site as intended, or things that would actively harm the site in the off chance that someone decides to try something funny. I feel like posting literally every single extreme edge case you come across does nothing but bloat the tracker and make it a lot harder for people to find and fix critical issues.

**Comment by meshuggahtas** [comment] 2022-04-12 06:57
I was about to write a new comment to be sure we are on the same track. Monospace is widely used in faq's to show the layout of levels and other route strategies for example Darius level strategies.

It's perfectly fine to disallow ASCII arts (posting text graphics that doesn't contribute to TASing in anyway).

I think supporting Monospace to get correct level layouts should benefit TASers.

If it doesn't, just close this issue and say "we don't want to support ASCII arts. go and open those TXT files yourself".

**Comment by CasualPokePlayer** [comment] 2022-04-12 06:59
https://github.com/TASVideos/tasvideos/labels
We have labels for a reason, low priority issues get [Priority: Bottom](https://github.com/TASVideos/tasvideos/labels/Priority%3A%20Bottom).

**Comment by CasualPokePlayer** [comment] 2022-04-12 07:16
A bug is a bug. It should be posted on the issue tracker. It will be closed when it is fixed or if it's unfixable (i.e. not our problem).

If there is a concern about bloat, then labels are not being used enough. Labels filter issues. These should be applied consistently across issues. If they are not, then you get unfilterable bloat.

**Comment by meshuggahtas** [comment] 2022-04-12 07:20
I think I made a good job with labeling a lot of issues. I refrain from creating new labels because I didn't wanted to introduce new terms without the developers knowing what I've meant for them (avoiding confusion). I would like to request appropriate labels for issues that doesn't have labels so I can apply it to them.

Note there's only 6 open issues without labels https://github.com/TASVideos/tasvideos/issues?q=is%3Aopen+is%3Aissue+no%3Alabel

**Comment by nattthebear** [comment] 2022-04-12 15:02
The behaviors on Chrome (Windows) and Firefox (Windows) are fine and expected.  Monospace fonts don't in general guarantee precisely identical character heights on all glyphs, only that the horizontal spacing is even.

The behaviors on the mobile devices are pretty bad.  Looks like we're using a Bootstrap provided font stack?  I'm surprised it would be such a train wreck on such common devices.  Do our source code tags have working monospace behavior?  If so, we could use that font.

I'd like us to get to the point where monospace is actually monospace, but ascii art as an artform is way too fontface and renderer specific to guarantee any particular compatibility.

**Comment by Masterjun3** [comment] 2024-08-22 21:45
I'm closing this issue.
From the site's perspective, we instruct the browser and OS to display the text in a monospace font. That's all we can do.
If a font doesn't have data for a certain glyph it will use a fallback font. And this fallback font's glyph might not be the same width.

This is just like someone posting a newly released emoji on the forums that some devices haven't supported yet. If you aren't careful, some people can't see what you're posting. So if you post monospace with frequently used characters, many fonts support that, so many people can see it properly. If you don't, then people don't see it properly.
The site can't do anything about this. This isn't a bug on our side.

If anyone has any specific monospace font that is widely supported and that they know can improve some frequent monospace characters better than our current monospace stack, then you can suggest that. But currently it doesn't make sense to have this issue ticket open, because there is no perfect solution, and we already do the best we think we can.

**Closed by Masterjun3** 2024-08-22 21:45 UTC
Labels: bug, Wiki Markup, Priority: Bottom
