### ISSUE TITLE
No forum markup buttons for PMs

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#990] opened 2022-01-15 19:58 UTC
![изображение](https://user-images.githubusercontent.com/7092625/149635993-4885e8dd-fc7d-4390-8c50-40122dbf2188.png)

I hope it's not by design, because forum PMs would be much harder to use productively if all forum tags had to be entered by hand.

**Comment by adelikat** [comment] 2022-01-15 19:59
It's not by design

**Comment by Masterjun3** [comment] 2022-02-25 01:07
This was also fixed by #1123.

**Closed by Masterjun3** 2022-02-25 01:07 UTC
Labels: enhancement, Forum System
