### ISSUE TITLE
I was able to log in only once

### ISSUE THREAD

**Issue by JosJuice** [TASVideos/tasvideos#759] opened 2022-01-03 20:38 UTC
I'm not sure if this actually is a site bug or rather some kind of user error or database anomaly, but I was directed here from the Discord, so here goes. Feel free to close this if it isn't a bug.

In the first hour of the new site going live, I was able to log in to my existing account JosJuice without any problems. I read a few forum posts, and changed the timezone and pronoun settings for my account. (Why was my timezone set to the first one in the list, anyway? Has it been set to that ever since the old site...?)

After that, I haven't been able to log in. The login page says "Invalid login attempt" even though I'm using the same password as before. I also tried using "Forgot your password?", and the site said "Please check your email to reset your password" after filling in my email address, but no email arrived. (I wasn't sure which of my two email addresses is in use for my account on this site, so I tried both, but the result was the same for both of them.)

**Comment by adelikat** [comment] 2022-01-03 22:05
Is your username on the site the same? JosJuice?

**Comment by adelikat** [comment] 2022-01-03 22:08
Nevermind, found your user.  looks like your email got set to unconfirmed by a bug that is now fixed.  I updated the database and you should be good to go now

**Closed by adelikat** 2022-01-03 22:08 UTC
