### ISSUE TITLE
Inserting username into wiki

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#42] opened 2018-05-11 20:43 UTC
In wikipedia, if you type ~~~ (or 4, or 5 tildes), your nickname and homepage link will be automatically inserted.
https://en.wikipedia.org/wiki/Wikipedia:Signatures

Tasvideos has special logic for [word] and for [user:x], the former explicitly links to the page fitting the word, and the latter does the check if such a homepage exists, and then links to it. This automatically handles things like lowercase username linking to a homepage that starts from a capital letter.

On the rewrite, lowercase usernames link nowhere when put as [adelikat], though the page they lead to suggests possibly intended link to Adelikat homepage. [user:adelikat] links to the homepage right away, even though it's lowercase initially.

So my request is to be able to automatically put your username with this homepage possibility feature. You type ~~~~ and save, TASVideoAgent turns it into [user:name]. Or like wikipedia, we could include some features depending on the amount of tildes, like adding a ruler above you if you type 5 of them.

**Comment by adelikat** [comment] 2022-03-20 13:35
I think what makes this not very feasible is that you need to know the user.  And by the time we are parsing the wiki markup, we no longer know the user.  @nattthebear : what do you think about this request.

(Also note that [user:adelikat] now links to the profile, not a homepage)

**Comment by nattthebear** [comment] 2022-03-20 15:48
This is supposed to insert a link to the user homepage of the person who made the edit, right?  So it's almost as simple as doing `Text = Text.Replace("~~~~", $"[user:{CurrentUser.Name}]")` on post creation.

**Comment by adelikat** [comment] 2022-03-20 15:49
Yeah, pretty much that

**Comment by nattthebear** [comment] 2022-03-20 16:02
This isn't too bad because it's not a change to the wiki system itself.

> On the rewrite, lowercase usernames link nowhere when put as [adelikat], though the page they lead to suggests possibly intended link to Adelikat homepage.

Do you want this changed?  I'm confused as to why it's mentioned here.  IIRC it's intended behavior.

**Comment by adelikat** [comment] 2022-03-20 16:10
I think that is outdated info.  Now, for legacy support, if you navigate to a page that is a valid username it will redirect to the homepage.  We do not want any change in this behavior, and these shenanigans are only for misbehaving users who weren't using the user module (looks at feos)

**Comment by adelikat** [comment] 2022-07-25 13:35
Do we still want this?  Is it really such a timer saver to type ~~~~ instead of [user:username] ?

**Comment by MemoryTAS** [comment] 2022-07-25 14:12
Wikipedia gets a lot more use out of it than we would because they have wiki based talk pages. We have a separate forum system so it's not as needed. The main use case is for people who don't remember to type the "user" part ie feos, but if there's already a redirect system, it's not that big a deal imo.

**Comment by adelikat** [comment] 2022-07-25 16:20
well, [username] is a hack workaround.  I'd argue Broken Links is doing its job to alert this misuse so we can fix them appropriately.

**Comment by adelikat** [comment] 2022-07-25 16:21
One day (it will be a long time from now), I will fix all usages of [username] and then drop support for that work around.  Does this fact settle the question about doing this ticket?

**Comment by MemoryTAS** [comment] 2022-07-25 16:34
Well you could also just pester people to use the right syntax. The only time a self [user:USERNAME] is used is on submissions by judges and publishers. I dunno if that's often enough to really warrant it.

**Comment by vadosnaprimer** [comment] 2022-07-25 17:12
If avoiding repetition via automation is not allowed, I'd rather just type `feos: ` without the brackets than add the thing I requested to be able to avoid. Having the `Claim` button helps, but being able to append a ruler together with your formatted name would be much better.

**Comment by Masterjun3** [comment] 2022-07-25 17:23
Less intrusive would be a javascript keyboard shortcut or something to insert the `[user:username]` to the current text position.
This issue seems less about making the server do hard work for you (adding precise date data), and more about making the users typing easier.

**Comment by adelikat** [comment] 2022-07-25 18:36
Feos on discord suggested buttons (that execute the javascript) in addition, similar to the forum bar, and I think that is the way to go here.  I think Masterjun got to the crux of the problem which includes a much simpler approach to the problem

**Comment by adelikat** [comment] 2022-07-25 19:36
Closing this in favor of the solution of having helpful buttons and hotkeys: https://github.com/TASVideos/tasvideos/issues/1381

**Closed by adelikat** 2022-07-25 19:36 UTC
Labels: enhancement, Wiki System
