### ISSUE TITLE
500 error when editing a submission's status and description simultaneously

### ISSUE THREAD

**Issue by despoa** [TASVideos/tasvideos#1399] opened 2022-08-12 02:47 UTC
When editing a submission's status and description in the same session and then saving, a "Sever Error Code 500" page pops up immediately. The change still takes effect and is still recorded in the history (except for the Discord bot), but this has happened consistently.

**Comment by adelikat** [comment] 2022-08-12 20:57
Doesn't happen for me, and doing both is pretty common, since you would put a blurb in the description while changing status.  Is anyone else having this issue?

**Comment by despoa** [comment] 2022-08-13 02:30
It happens when I change the status from "Publication Underway" to "Accepted".

**Comment by adelikat** [comment] 2022-08-13 14:46
Weird. That worked for me too

**Comment by adelikat** [comment] 2022-08-21 20:50
Looking at the logs from about the time this is reported, it seems to be a DbUpdate exception when adding the wiki page.  Inner exception is not logs so I don't know what caused it.  I'd guess the unique constraint on page_name + revision, but I don't see how that can happen often enough to be reported, as it would require simultaneous edits by 2 users I think.

Not sure what is going on here

**Comment by adelikat** [comment] 2022-11-12 19:52
Thinking this is a db concurrency exception, as it seems rare.  If another user edited the submission at the same time, this could happen.

For regular wiki pages, there is a check in place for concurrent edits, but not on pubs/subs.  Not as easy there since it is wiki page plus other things.  I think that is the work that needs to be done to resolve this ticket

**Comment by vadosnaprimer** [comment] 2024-02-02 13:32
@despoa does it happen consistently or randomly or just once?

**Comment by adelikat** [comment] 2024-05-10 18:49
Closing, I think this was a transient error and non-consistently reproducible and have not heard of a report of it happening since.

**Closed by adelikat** 2024-05-10 18:49 UTC
Labels: bug, Submission System, backend
