### ISSUE TITLE
Images with redirects won't show up

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#1148] opened 2022-03-10 19:07 UTC
This affects any images with 301 Redirect.

Examples:
- Profile https://tasvideos.org/Users/Profile/alden
- Original image link http://aldentas.googlepages.com/bob.gif
- Redirected image link http://sites.google.com/site/aldentas2/bob.gif 
---
- Profile https://tasvideos.org/Users/Profile/Spoony_Bard
- Original image link http://www.rpgclassics.com/~onlinelife/images/Wario.gif
- Redirected image link http://onlinelife.rpgclassics.com/images/Wario.gif

edit: I'm unsure about is it really affects all types of images. Maybe only gif files affected? I've found a working .png redirected image here: https://tasvideos.org/HomePages/alden/Exhibitions/AVGN

**Comment by Masterjun3** [comment] 2022-03-10 19:17
The issue is that the link is HTTP. We use HTTPS and can't serve HTTP resources.
Browsers may try to connect insecure links with HTTPS, but if it doesn't work it is just a broken link, to be fixed by the user.

Nothing to be done here from the code's perspective.

**Closed by Masterjun3** 2022-03-10 19:17 UTC
