### ISSUE TITLE
When an Emulator is Searched. Prioritize the Emulator's Page of Release, Subpage (Hawk's case), then Encoding Guide then Everything Else.

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/tasvideos#1908] opened 2024-07-01 18:33 UTC
Yes I know the existence of Articles > Emulators > [Emulator] but personally I prefer the simplicity of going "this is what I want, I don't want to go through a table". Or in [Potential Emulators'](https://tasvideos.org/EmulatorResources/PotentialEmulators) case remembering where in the blazes to go for that.

BizHawk's issue we have Previous Release History *above* Release History, where it should be the other way around.
![image](https://github.com/TASVideos/tasvideos/assets/12412764/18da58db-f0bc-4d68-a7ed-402de15cf4bf)
And yes, it doesn't make the argument for the case of this-- however.

When searching up Mupen I only have Submissions, a "Hall of Shame" and an Instruction Guide on how to dump for encodes but not the page about [the Emulator itself](https://tasvideos.org/EmulatorResources/Mupen).
![image](https://github.com/TASVideos/tasvideos/assets/12412764/931851b5-e648-4489-be65-f4b03abe77cf)

This also extends to the mentioned Encoding Guide, where it would help for it to go to its headed (this is probably not feasible), but at least getting its page would help as well.

**Comment by YoshiRulz** [comment] 2024-07-01 18:38
Duplicate of #1674?

**Comment by adelikat** [comment] 2024-07-03 15:47
We simply can't do this via search algorithm logic.  But take a look at #1674 , putting text into the wiki will help put more relevant pages higher on the list

**Closed by adelikat** 2024-07-03 15:47 UTC
Labels: enhancement, Search
