### ISSUE TITLE
Stop double-compressing movie files

### ISSUE THREAD

**Issue by YoshiRulz** [TASVideos/tasvideos#1045] opened 2022-01-24 02:26 UTC

**Comment by meshuggahtas** [comment] 2022-01-24 21:12
I assume this is about TAS movies uploaded as userfiles and submissions being in a zip formatted movie format, which is probably only supported and allowed to use emulator is BizHawk. Unsure about lsmv for lsnes.

**Comment by adelikat** [comment] 2022-09-02 01:51
Closing this as a duplicate of https://github.com/TASVideos/tasvideos/issues/1187

I agree we should allow uploading a movie file without it being zipped but it was really difficult to implement while backwards supporting legacy data.  It's more feasible now that we don't have a legacy site to worry about but it still requires rethinking the most complicated pages on the site.

**Closed by adelikat** 2022-09-02 01:51 UTC
Labels: enhancement, Movie Parsers
