### ISSUE TITLE
When editing user file text, the game name is reset

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/tasvideos#1578] opened 2023-06-20 02:24 UTC
Title says it all. I made several edits to the description of [this user file](https://tasvideos.org/UserFiles/Info/638228175092136443), and each time I had to re-select from the `Game` listing. `System` was properly retained, though.

I'm fairly sure I've seen this happen with other user files.

**Comment by RetroEdit** [comment] 2023-07-11 17:44
I had a look at this. From tweaking the code a bit, I guess it's somewhere in here:

https://github.com/TASVideos/tasvideos/blob/main/TASVideos/Pages/UserFiles/Edit.cshtml.cs#L94-L115

Although I think the defaults for the dropdown list are actually handled here:

https://github.com/TASVideos/tasvideos/blob/main/TASVideos/Pages/UserFiles/Edit.cshtml#L42-L51

I'm not sure why it *does* select the default properly for `Userfile.SystemId`, but fails to select the default for `Userfile.GameId`.

Also, when you watch the edit page load, you see it flicker with the correct `GameId` for a moment, but then it reverts to the default non-selection entry `---` at the top of the list.

**Comment by Masterjun3** [comment] 2023-07-11 17:49
It's because the javascript `enableUserFile` is executed at the bottom of the site. The whole innerHTML of the select is then overwritten via the userfile.js file. And this resets the selection.
https://github.com/TASVideos/tasvideos/blob/9ca8e125e34d510018cb62de273bd7aa1e4ef83a/TASVideos/wwwroot/js/userfile.js#L10

**Comment by Masterjun3** [comment] 2023-07-11 17:53
Oh, looks like this issue was caused by the fix for this issue #1391 .
Any PR fixing this one should make sure the other one isn't rebugged, I think.

My quick idea would be to edit the userfile.js to save the selection, if any, and restore it after replacing the innerHTML

**Closed** 2023-07-11 18:42 UTC
