### ISSUE TITLE
Site Blacklisting

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/tasvideos#1924] opened 2024-07-28 12:44 UTC
This happens enough times where it's a justifiable thing to prevent **a user** to Create a Post or Submission.

If it's possible to basically throw an error, when a site provides pre-patched roms that it throws an exception informing people to actually be sure that their patch is firstly available on [ROMHacking.net](https://www.romhacking.net/) or extracted as an ips/bps/xdelta (etc) and is available on a google drive for instance.

Two sites that we can experiment this blacklist on are Sonic Retro and CDRomance.
If name dropping them was too much for the issue request you can simply remove the example target sites and all would still be good (hopefully).

**Comment by YoshiRulz** [comment] 2024-07-28 12:47
Duplicate of #1460.

**Closed by YoshiRulz** 2024-07-28 12:47 UTC
Labels: duplicate, enhancement, anti-abuse
